baseURL: https://kenodegard.github.io
languageCode: en-us
title: Dev Thoughts
theme: PaperMod

params:
  homeInfoParams:
    title: ğŸ‘‹ğŸ¼ Here's some of Ken's musings! Don't take any of this too seriously! ğŸ’­
    content: ğŸ‘¨ğŸ¼â€ğŸ’» ğŸ“– ğŸ° ğŸª´ ğŸ¥¾ ğŸ§³ âœˆï¸ â˜•ï¸ ğŸ¹ ğŸŒ® ğŸ‡³ğŸ‡´ ğŸ³ï¸â€ğŸŒˆ âœŠğŸ¿ âœŠğŸ¾ âœŠğŸ½

  socialIcons:
    - name: github
      url: https://github.com/kenodegard
    - name: twitter
      url: https://twitter.com/ken_odegard
    - name: linkedin
      url: https://www.linkedin.com/in/kenodegard

  showShareButtons: true
  showReadingTime: true
  showCodeCopyButtons: true
